import { Leaf, Shield, Cpu } from "lucide-react";

/**
 * Generates realistic stock-like price history using random walk with volatility
 * @param startPrice Starting price
 * @param endPrice Target ending price
 * @param days Number of days to generate
 * @param volatility Base volatility (0.01 = 1% daily moves)
 * @returns Array of price points
 */
function generatePriceHistory(
  startPrice: number,
  endPrice: number,
  days: number = 30,
  volatility: number = 0.03
): number[] {
  const prices: number[] = [startPrice];
  let currentPrice = startPrice;

  // Calculate target drift per day to reach endPrice
  const totalDrift = (endPrice - startPrice) / days;

  // Seed for consistent randomness per company (based on startPrice)
  let seed = Math.floor(startPrice * 1000) % 10000;

  const random = () => {
    seed = (seed * 9301 + 49297) % 233280;
    return seed / 233280;
  };

  for (let i = 1; i < days; i++) {
    // Random walk with drift
    const randomChange = (random() - 0.5) * 2; // -1 to 1
    const volatilityFactor = volatility * (0.5 + random() * 1.5); // Variable volatility
    const dailyChange = currentPrice * volatilityFactor * randomChange;

    // Add drift toward target
    const drift = totalDrift * (1 + (random() - 0.5) * 0.3);

    // Occasional larger moves (10% chance of 2-4x normal move)
    let move = dailyChange + drift;
    if (random() < 0.1) {
      move *= 2 + random() * 2; // 2x to 4x normal move
    }

    currentPrice = Math.max(0.1, currentPrice + move);

    // Occasional momentum (trend persistence)
    if (i > 1 && random() < 0.3) {
      const momentum = (currentPrice - prices[i - 2]) * 0.3;
      currentPrice += momentum;
    }

    prices.push(Math.round(currentPrice * 100) / 100);
  }

  // Adjust final price to match target (smooth interpolation)
  const lastIndex = prices.length - 1;
  const adjustment = (endPrice - prices[lastIndex]) * 0.3;
  prices[lastIndex] = Math.round((prices[lastIndex] + adjustment) * 100) / 100;

  // Final smoothing pass to ensure we end at target
  if (Math.abs(prices[lastIndex] - endPrice) > 0.1) {
    prices[lastIndex] = endPrice;
  }

  return prices;
}

export interface Opportunity {
  id: string;
  name: string;
  tagline: string;
  sector: string;
  vertical: string;
  stage: string;
  location: string;
  foundingYear: number;
  sharesAvailablePercent: number;
  valuation: string;
  minInvestment: number;
  runwayMonths: number;
  fundingProgress: number;
  euDomiciled: boolean;
  audited: boolean;
  founderName?: string;
  founderTitle?: string;
  leadInvestor?: string;
  impactHeadline?: string;
  businessHook?: string;
  sharePrice: number;
  priceHistory: number[];
  votingPremium: number;
  votingPremiumType: "percentage" | "fixed";
  startupId?: number; // Link to blockchain StartupRegistry contract
}

export interface ThematicCollection {
  id: string;
  title: string;
  description: string;
  icon: React.ReactNode;
  sectors: string[];
}

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    name: "SkyMed Delivery",
    tagline: "Autonomous drone delivery for rural pharmacies",
    sector: "HealthTech",
    vertical: "Medical Logistics",
    stage: "Seed",
    location: "Germany",
    foundingYear: 2021,
    sharesAvailablePercent: 12,
    valuation: "€8M",
    minInvestment: 100,
    runwayMonths: 6,
    fundingProgress: 65,
    euDomiciled: true,
    audited: true,
    founderName: "Dr. Anna Müller",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "High-Tech Gründerfonds",
    impactHeadline: "Bringing Essential Medicine to Rural Germany",
    businessHook:
      "Autonomous drone network delivering pharmaceuticals to 2,400+ rural pharmacies. Pilots active with AOK and Deutsche Post.",
    sharePrice: 12.45,
    priceHistory: generatePriceHistory(10.2, 12.45, 30, 0.035),
    votingPremium: 0.15,
    votingPremiumType: "percentage",
    startupId: 0, // Linked to blockchain StartupRegistry
  },
  {
    id: "2",
    name: "GreenGrid Energy",
    tagline: "AI-optimized solar panel networks for SMEs",
    sector: "CleanTech",
    vertical: "Renewable Energy",
    stage: "Series A",
    location: "Netherlands",
    foundingYear: 2019,
    sharesAvailablePercent: 8,
    valuation: "€22M",
    minInvestment: 250,
    runwayMonths: 14,
    fundingProgress: 42,
    euDomiciled: true,
    audited: true,
    founderName: "Lars van der Berg",
    founderTitle: "CEO & Founder",
    leadInvestor: "EQT Ventures",
    impactHeadline: "Democratizing Solar Energy for European SMEs",
    businessHook:
      "AI-driven solar optimization reducing energy costs by 40% for small businesses. 340 installations across Benelux.",
    sharePrice: 18.75,
    priceHistory: generatePriceHistory(17.2, 18.75, 30, 0.028),
    votingPremium: 0.12,
    votingPremiumType: "percentage",
  },
  {
    id: "3",
    name: "FarmSense",
    tagline: "Precision agriculture sensors for European farmers",
    sector: "AgriTech",
    vertical: "Precision Farming",
    stage: "Seed",
    location: "France",
    foundingYear: 2022,
    sharesAvailablePercent: 15,
    valuation: "€5M",
    minInvestment: 50,
    runwayMonths: 9,
    fundingProgress: 78,
    euDomiciled: true,
    audited: false,
    founderName: "Marie Dubois",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Partech Partners",
    impactHeadline: "Feeding Europe with Precision Agriculture",
    businessHook:
      "IoT sensors reducing water usage by 35% and increasing crop yields. Deployed across 1,200 hectares in France.",
    sharePrice: 8.2,
    priceHistory: generatePriceHistory(7.1, 8.2, 30, 0.042),
    votingPremium: 1.5,
    votingPremiumType: "fixed",
  },
  {
    id: "4",
    name: "SecureID Labs",
    tagline: "Decentralized identity verification for banks",
    sector: "FinTech",
    vertical: "Identity & Security",
    stage: "Series A",
    location: "Austria",
    foundingYear: 2020,
    sharesAvailablePercent: 6,
    valuation: "€15M",
    minInvestment: 500,
    runwayMonths: 18,
    fundingProgress: 31,
    euDomiciled: true,
    audited: true,
    founderName: "Thomas Weber",
    founderTitle: "CEO & CTO",
    leadInvestor: "Speedinvest",
    impactHeadline: "Building Trust in European Digital Banking",
    businessHook:
      "Privacy-first identity verification reducing KYC costs by 60%. Integrated with Erste Bank and N26.",
    sharePrice: 15.3,
    priceHistory: generatePriceHistory(13.8, 15.3, 30, 0.032),
    votingPremium: 0.18,
    votingPremiumType: "percentage",
  },
  {
    id: "5",
    name: "MediBot",
    tagline: "AI diagnostic assistant for rural clinics",
    sector: "HealthTech",
    vertical: "AI Diagnostics",
    stage: "Pre-Seed",
    location: "Spain",
    foundingYear: 2023,
    sharesAvailablePercent: 20,
    valuation: "€3M",
    minInvestment: 100,
    runwayMonths: 4,
    fundingProgress: 89,
    euDomiciled: true,
    audited: false,
    founderName: "Dr. Carlos Ruiz",
    founderTitle: "CEO & Chief Medical Officer",
    leadInvestor: "Kibo Ventures",
    impactHeadline: "Closing the Rural Healthcare Gap in Spain",
    businessHook:
      "AI-powered diagnostics supporting rural doctors with 94% accuracy. Active in 45 clinics across Andalusia.",
    sharePrice: 5.85,
    priceHistory: generatePriceHistory(4.8, 5.85, 30, 0.045),
    votingPremium: 0.1,
    votingPremiumType: "percentage",
  },
  {
    id: "6",
    name: "CircularPack",
    tagline: "Reusable packaging logistics for e-commerce",
    sector: "CleanTech",
    vertical: "Circular Economy",
    stage: "Seed",
    location: "Belgium",
    foundingYear: 2021,
    sharesAvailablePercent: 10,
    valuation: "€6M",
    minInvestment: 150,
    runwayMonths: 11,
    fundingProgress: 55,
    euDomiciled: true,
    audited: true,
    founderName: "Sophie Janssen",
    founderTitle: "CEO & Founder",
    leadInvestor: "Fortino Capital",
    impactHeadline: "Eliminating E-commerce Packaging Waste",
    businessHook:
      "Reusable packaging system eliminating 2M+ single-use boxes annually. Partnerships with Zalando and Coolblue.",
    sharePrice: 9.6,
    priceHistory: generatePriceHistory(8.9, 9.6, 30, 0.038),
    votingPremium: 2.0,
    votingPremiumType: "fixed",
  },
  {
    id: "7",
    name: "Mistral AI",
    tagline:
      "Building open-source large language models for European AI sovereignty",
    sector: "DeepTech",
    vertical: "Artificial Intelligence",
    stage: "Series B",
    location: "France",
    foundingYear: 2023,
    sharesAvailablePercent: 3,
    valuation: "€5.8B",
    minInvestment: 1000,
    runwayMonths: 36,
    fundingProgress: 22,
    euDomiciled: true,
    audited: true,
    founderName: "Arthur Mensch",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Andreessen Horowitz",
    impactHeadline: "Building Europe's Answer to OpenAI",
    businessHook:
      "Open-weight LLMs rivaling GPT-4 at a fraction of the cost. Partnerships with Microsoft, IBM, and European governments.",
    sharePrice: 245.8,
    priceHistory: generatePriceHistory(210.0, 245.8, 30, 0.025),
    votingPremium: 0.2,
    votingPremiumType: "percentage",
  },
  {
    id: "8",
    name: "EduFlow",
    tagline: "AI-powered personalized learning platform for European schools",
    sector: "EdTech",
    vertical: "K-12 Education",
    stage: "Seed",
    location: "Sweden",
    foundingYear: 2022,
    sharesAvailablePercent: 14,
    valuation: "€7M",
    minInvestment: 100,
    runwayMonths: 8,
    fundingProgress: 72,
    euDomiciled: true,
    audited: false,
    founderName: "Erik Andersson",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Creandum",
    impactHeadline: "Transforming Education Across Nordic Schools",
    businessHook:
      "Personalized learning paths improving test scores by 28%. Active in 180 schools across Sweden and Norway.",
    sharePrice: 10.5,
    priceHistory: generatePriceHistory(9.0, 10.5, 30, 0.04),
    votingPremium: 0.12,
    votingPremiumType: "percentage",
  },
  {
    id: "9",
    name: "PropTech Solutions",
    tagline: "Smart building management for commercial real estate",
    sector: "PropTech",
    vertical: "Building Automation",
    stage: "Series A",
    location: "Denmark",
    foundingYear: 2020,
    sharesAvailablePercent: 7,
    valuation: "€18M",
    minInvestment: 300,
    runwayMonths: 16,
    fundingProgress: 38,
    euDomiciled: true,
    audited: true,
    founderName: "Lars Nielsen",
    founderTitle: "CEO & Founder",
    leadInvestor: "Northzone",
    impactHeadline: "Making Buildings Smarter Across Scandinavia",
    businessHook:
      "IoT platform reducing energy consumption by 32% in commercial buildings. Managing 450+ properties across Denmark.",
    sharePrice: 16.8,
    priceHistory: generatePriceHistory(15.1, 16.8, 30, 0.03),
    votingPremium: 0.16,
    votingPremiumType: "percentage",
  },
  {
    id: "10",
    name: "FoodWaste AI",
    tagline: "AI-powered food waste reduction for restaurants",
    sector: "FoodTech",
    vertical: "Sustainability",
    stage: "Pre-Seed",
    location: "Italy",
    foundingYear: 2023,
    sharesAvailablePercent: 18,
    valuation: "€4M",
    minInvestment: 75,
    runwayMonths: 5,
    fundingProgress: 82,
    euDomiciled: true,
    audited: false,
    founderName: "Marco Rossi",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "P101",
    impactHeadline: "Eliminating Food Waste in European Restaurants",
    businessHook:
      "Predictive analytics reducing food waste by 45%. Deployed in 320 restaurants across Italy and Spain.",
    sharePrice: 6.2,
    priceHistory: generatePriceHistory(5.3, 6.2, 30, 0.048),
    votingPremium: 1.0,
    votingPremiumType: "fixed",
  },
  {
    id: "11",
    name: "MobilityHub",
    tagline:
      "Integrated urban mobility platform connecting all transport modes",
    sector: "MobilityTech",
    vertical: "Transportation",
    stage: "Series A",
    location: "Netherlands",
    foundingYear: 2021,
    sharesAvailablePercent: 9,
    valuation: "€12M",
    minInvestment: 200,
    runwayMonths: 12,
    fundingProgress: 48,
    euDomiciled: true,
    audited: true,
    founderName: "Emma van der Berg",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "HV Capital",
    impactHeadline: "Unifying European Urban Mobility",
    businessHook:
      "Single app integrating trains, buses, bikes, and scooters. 85K active users across Amsterdam, Rotterdam, and Utrecht.",
    sharePrice: 13.4,
    priceHistory: generatePriceHistory(11.8, 13.4, 30, 0.033),
    votingPremium: 0.14,
    votingPremiumType: "percentage",
  },
  {
    id: "12",
    name: "CarbonLedger",
    tagline: "Enterprise carbon accounting platform using AI",
    sector: "CleanTech",
    vertical: "Carbon Management",
    stage: "Seed",
    location: "Germany",
    foundingYear: 2021,
    sharesAvailablePercent: 11,
    valuation: "€9M",
    minInvestment: 150,
    runwayMonths: 10,
    fundingProgress: 61,
    euDomiciled: true,
    audited: true,
    founderName: "Anna Schmidt",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Earlybird Venture Capital",
    impactHeadline: "Automating Carbon Accounting for European Enterprises",
    businessHook:
      "AI-powered platform automatically tracking emissions across supply chains. Serving 45+ enterprises including Siemens and BASF.",
    sharePrice: 11.2,
    priceHistory: generatePriceHistory(9.8, 11.2, 30, 0.036),
    votingPremium: 1.8,
    votingPremiumType: "fixed",
  },
  {
    id: "13",
    name: "BioPharm Innovations",
    tagline: "Next-generation biopharmaceutical manufacturing",
    sector: "BioTech",
    vertical: "Pharmaceuticals",
    stage: "Series B",
    location: "Switzerland",
    foundingYear: 2019,
    sharesAvailablePercent: 4,
    valuation: "€45M",
    minInvestment: 750,
    runwayMonths: 24,
    fundingProgress: 28,
    euDomiciled: true,
    audited: true,
    founderName: "Dr. Sophie Müller",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Index Ventures",
    impactHeadline: "Revolutionizing European Biopharmaceutical Production",
    businessHook:
      "Novel manufacturing process reducing production costs by 50%. Partnerships with Novartis and Roche.",
    sharePrice: 42.5,
    priceHistory: generatePriceHistory(38.5, 42.5, 30, 0.022),
    votingPremium: 0.22,
    votingPremiumType: "percentage",
  },
  {
    id: "14",
    name: "QuantumSecure",
    tagline: "Quantum-resistant encryption for critical infrastructure",
    sector: "DeepTech",
    vertical: "Cybersecurity",
    stage: "Seed",
    location: "Finland",
    foundingYear: 2022,
    sharesAvailablePercent: 13,
    valuation: "€6.5M",
    minInvestment: 100,
    runwayMonths: 7,
    fundingProgress: 68,
    euDomiciled: true,
    audited: false,
    founderName: "Jukka Virtanen",
    founderTitle: "CEO & CTO",
    leadInvestor: "Lifeline Ventures",
    impactHeadline: "Protecting Europe's Critical Infrastructure",
    businessHook:
      "Post-quantum cryptography protecting against future quantum attacks. Deployed in 12 critical infrastructure projects.",
    sharePrice: 8.9,
    priceHistory: generatePriceHistory(7.6, 8.9, 30, 0.041),
    votingPremium: 0.11,
    votingPremiumType: "percentage",
  },
  {
    id: "15",
    name: "AgriData Analytics",
    tagline: "Predictive analytics for crop yield optimization",
    sector: "AgriTech",
    vertical: "Data Analytics",
    stage: "Pre-Seed",
    location: "Poland",
    foundingYear: 2023,
    sharesAvailablePercent: 19,
    valuation: "€3.5M",
    minInvestment: 50,
    runwayMonths: 4,
    fundingProgress: 91,
    euDomiciled: true,
    audited: false,
    founderName: "Katarzyna Nowak",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Inovo Venture Partners",
    impactHeadline: "Boosting Crop Yields Across Central Europe",
    businessHook:
      "Machine learning models predicting optimal planting times and crop selection. Piloted on 800 hectares in Poland.",
    sharePrice: 5.4,
    priceHistory: generatePriceHistory(4.6, 5.4, 30, 0.05),
    votingPremium: 0.08,
    votingPremiumType: "percentage",
  },
  {
    id: "16",
    name: "FinFlow",
    tagline: "Automated accounting for small businesses",
    sector: "FinTech",
    vertical: "Accounting Software",
    stage: "Series A",
    location: "Portugal",
    foundingYear: 2020,
    sharesAvailablePercent: 8,
    valuation: "€14M",
    minInvestment: 250,
    runwayMonths: 15,
    fundingProgress: 44,
    euDomiciled: true,
    audited: true,
    founderName: "João Silva",
    founderTitle: "CEO & Founder",
    leadInvestor: "Indico Capital Partners",
    impactHeadline: "Simplifying Accounting for European SMEs",
    businessHook:
      "AI-powered bookkeeping saving 10 hours per week. Serving 2,400+ small businesses across Portugal and Spain.",
    sharePrice: 14.6,
    priceHistory: generatePriceHistory(13.2, 14.6, 30, 0.031),
    votingPremium: 0.17,
    votingPremiumType: "percentage",
  },
  {
    id: "17",
    name: "HealthMonitor Pro",
    tagline: "Remote patient monitoring for chronic conditions",
    sector: "HealthTech",
    vertical: "Digital Health",
    stage: "Seed",
    location: "Ireland",
    foundingYear: 2021,
    sharesAvailablePercent: 12,
    valuation: "€8.5M",
    minInvestment: 100,
    runwayMonths: 9,
    fundingProgress: 63,
    euDomiciled: true,
    audited: true,
    founderName: "Dr. Sarah O'Brien",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Frontline Ventures",
    impactHeadline: "Improving Chronic Disease Management in Europe",
    businessHook:
      "Wearable devices and AI monitoring 1,200+ patients with diabetes and hypertension. Reducing hospitalizations by 35%.",
    sharePrice: 12.8,
    priceHistory: generatePriceHistory(11.2, 12.8, 30, 0.037),
    votingPremium: 1.6,
    votingPremiumType: "fixed",
  },
  {
    id: "18",
    name: "WindOpt AI",
    tagline: "AI-optimized wind farm operations",
    sector: "CleanTech",
    vertical: "Wind Energy",
    stage: "Series A",
    location: "Denmark",
    foundingYear: 2020,
    sharesAvailablePercent: 7,
    valuation: "€20M",
    minInvestment: 300,
    runwayMonths: 17,
    fundingProgress: 35,
    euDomiciled: true,
    audited: true,
    founderName: "Mads Hansen",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Atomico",
    impactHeadline: "Maximizing Wind Energy Output Across Europe",
    businessHook:
      "Machine learning optimizing turbine performance increasing energy output by 18%. Managing 12 wind farms across Denmark.",
    sharePrice: 19.2,
    priceHistory: generatePriceHistory(17.0, 19.2, 30, 0.029),
    votingPremium: 0.19,
    votingPremiumType: "percentage",
  },
  {
    id: "19",
    name: "BlockchainPay",
    tagline: "Cryptocurrency payment infrastructure for merchants",
    sector: "FinTech",
    vertical: "Payments",
    stage: "Pre-Seed",
    location: "Estonia",
    foundingYear: 2023,
    sharesAvailablePercent: 17,
    valuation: "€4.5M",
    minInvestment: 75,
    runwayMonths: 5,
    fundingProgress: 85,
    euDomiciled: true,
    audited: false,
    founderName: "Marten Kask",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Superangel",
    impactHeadline: "Bringing Crypto Payments to European Commerce",
    businessHook:
      "Seamless crypto-to-fiat conversion for merchants. Integrated with 180+ online stores across the Baltics.",
    sharePrice: 6.7,
    priceHistory: generatePriceHistory(5.8, 6.7, 30, 0.046),
    votingPremium: 0.09,
    votingPremiumType: "percentage",
  },
  {
    id: "20",
    name: "RoboCare",
    tagline: "Assistive robots for elderly care facilities",
    sector: "HealthTech",
    vertical: "Robotics",
    stage: "Seed",
    location: "Netherlands",
    foundingYear: 2022,
    sharesAvailablePercent: 14,
    valuation: "€7.5M",
    minInvestment: 100,
    runwayMonths: 8,
    fundingProgress: 70,
    euDomiciled: true,
    audited: false,
    founderName: "Dr. Pieter de Vries",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Health Innovations",
    impactHeadline: "Supporting Europe's Aging Population",
    businessHook:
      "Social robots assisting with daily tasks in 28 care facilities. Reducing caregiver workload by 25%.",
    sharePrice: 10.8,
    priceHistory: generatePriceHistory(9.3, 10.8, 30, 0.039),
    votingPremium: 1.3,
    votingPremiumType: "fixed",
  },
  {
    id: "21",
    name: "WaterSense",
    tagline: "Smart water management for municipalities",
    sector: "CleanTech",
    vertical: "Water Management",
    stage: "Series A",
    location: "Spain",
    foundingYear: 2021,
    sharesAvailablePercent: 9,
    valuation: "€11M",
    minInvestment: 200,
    runwayMonths: 13,
    fundingProgress: 52,
    euDomiciled: true,
    audited: true,
    founderName: "Carmen García",
    founderTitle: "CEO & Founder",
    leadInvestor: "JME Ventures",
    impactHeadline: "Conserving Water Across European Cities",
    businessHook:
      "IoT sensors and AI reducing water loss by 28% in municipal systems. Deployed in 15 cities across Spain.",
    sharePrice: 12.2,
    priceHistory: generatePriceHistory(10.7, 12.2, 30, 0.034),
    votingPremium: 0.15,
    votingPremiumType: "percentage",
  },
  {
    id: "22",
    name: "LearnAI",
    tagline: "AI tutoring platform for university students",
    sector: "EdTech",
    vertical: "Higher Education",
    stage: "Seed",
    location: "United Kingdom",
    foundingYear: 2022,
    sharesAvailablePercent: 13,
    valuation: "€6.8M",
    minInvestment: 100,
    runwayMonths: 7,
    fundingProgress: 66,
    euDomiciled: true,
    audited: false,
    founderName: "James Mitchell",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "LocalGlobe",
    impactHeadline: "Personalizing Higher Education Across Europe",
    businessHook:
      "AI tutors providing 24/7 support for STEM subjects. 8,500+ active students across 12 universities.",
    sharePrice: 9.1,
    priceHistory: generatePriceHistory(7.9, 9.1, 30, 0.043),
    votingPremium: 1.2,
    votingPremiumType: "fixed",
  },
  {
    id: "23",
    name: "SmartGrid EU",
    tagline: "Intelligent grid management for renewable energy",
    sector: "CleanTech",
    vertical: "Grid Technology",
    stage: "Series B",
    location: "Germany",
    foundingYear: 2019,
    sharesAvailablePercent: 5,
    valuation: "€35M",
    minInvestment: 600,
    runwayMonths: 22,
    fundingProgress: 26,
    euDomiciled: true,
    audited: true,
    founderName: "Dr. Klaus Fischer",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Balderton Capital",
    impactHeadline: "Modernizing Europe's Energy Grid",
    businessHook:
      "AI-powered grid balancing enabling 40% renewable energy integration. Serving 8 regional grid operators.",
    sharePrice: 33.5,
    priceHistory: generatePriceHistory(29.5, 33.5, 30, 0.026),
    votingPremium: 0.21,
    votingPremiumType: "percentage",
  },
  {
    id: "24",
    name: "MedSupply Chain",
    tagline: "Blockchain-based pharmaceutical supply chain tracking",
    sector: "HealthTech",
    vertical: "Supply Chain",
    stage: "Pre-Seed",
    location: "Belgium",
    foundingYear: 2023,
    sharesAvailablePercent: 20,
    valuation: "€3.2M",
    minInvestment: 50,
    runwayMonths: 4,
    fundingProgress: 88,
    euDomiciled: true,
    audited: false,
    founderName: "Luc De Vries",
    founderTitle: "CEO & Founder",
    leadInvestor: "PMV",
    impactHeadline: "Ensuring Pharmaceutical Supply Chain Integrity",
    businessHook:
      "Immutable tracking preventing counterfeit drugs. Piloted with 3 major pharmaceutical distributors.",
    sharePrice: 5.1,
    priceHistory: generatePriceHistory(4.4, 5.1, 30, 0.052),
    votingPremium: 0.07,
    votingPremiumType: "percentage",
  },
  {
    id: "25",
    name: "InsurTech Pro",
    tagline: "AI-powered insurance underwriting platform",
    sector: "FinTech",
    vertical: "Insurance",
    stage: "Series A",
    location: "France",
    foundingYear: 2020,
    sharesAvailablePercent: 8,
    valuation: "€16M",
    minInvestment: 300,
    runwayMonths: 15,
    fundingProgress: 41,
    euDomiciled: true,
    audited: true,
    founderName: "Sophie Martin",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Partech",
    impactHeadline: "Revolutionizing Insurance Underwriting in Europe",
    businessHook:
      "Machine learning reducing underwriting time from days to minutes. Serving 12 insurance companies across France.",
    sharePrice: 17.2,
    priceHistory: generatePriceHistory(15.5, 17.2, 30, 0.027),
    votingPremium: 0.18,
    votingPremiumType: "percentage",
  },
  {
    id: "26",
    name: "AgriRobotics",
    tagline: "Autonomous robots for precision farming",
    sector: "AgriTech",
    vertical: "Agricultural Robotics",
    stage: "Seed",
    location: "Netherlands",
    foundingYear: 2021,
    sharesAvailablePercent: 11,
    valuation: "€8.8M",
    minInvestment: 150,
    runwayMonths: 10,
    fundingProgress: 58,
    euDomiciled: true,
    audited: true,
    founderName: "Willem Bakker",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Innovation Industries",
    impactHeadline: "Automating Precision Agriculture",
    businessHook:
      "Autonomous robots performing weeding and harvesting. Deployed across 600 hectares of Dutch farms.",
    sharePrice: 11.5,
    priceHistory: generatePriceHistory(10.1, 11.5, 30, 0.035),
    votingPremium: 1.7,
    votingPremiumType: "fixed",
  },
  {
    id: "27",
    name: "DeepCode AI",
    tagline: "AI-powered code review and security scanning",
    sector: "DeepTech",
    vertical: "Developer Tools",
    stage: "Series A",
    location: "Czech Republic",
    foundingYear: 2020,
    sharesAvailablePercent: 7,
    valuation: "€13M",
    minInvestment: 250,
    runwayMonths: 14,
    fundingProgress: 46,
    euDomiciled: true,
    audited: true,
    founderName: "Tomáš Novák",
    founderTitle: "CEO & CTO",
    leadInvestor: "Credo Ventures",
    impactHeadline: "Securing European Software Development",
    businessHook:
      "AI detecting bugs and security vulnerabilities in real-time. Used by 450+ development teams across Europe.",
    sharePrice: 15.8,
    priceHistory: generatePriceHistory(14.2, 15.8, 30, 0.032),
    votingPremium: 0.16,
    votingPremiumType: "percentage",
  },
  {
    id: "28",
    name: "RecycleAI",
    tagline: "AI-powered waste sorting and recycling optimization",
    sector: "CleanTech",
    vertical: "Waste Management",
    stage: "Pre-Seed",
    location: "Sweden",
    foundingYear: 2023,
    sharesAvailablePercent: 16,
    valuation: "€4.2M",
    minInvestment: 75,
    runwayMonths: 5,
    fundingProgress: 80,
    euDomiciled: true,
    audited: false,
    founderName: "Elin Larsson",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Inventure",
    impactHeadline: "Maximizing Recycling Rates Across Europe",
    businessHook:
      "Computer vision sorting waste with 95% accuracy. Deployed in 25 recycling facilities across Sweden.",
    sharePrice: 6.3,
    priceHistory: generatePriceHistory(5.4, 6.3, 30, 0.047),
    votingPremium: 0.1,
    votingPremiumType: "percentage",
  },
  {
    id: "29",
    name: "TeleHealth Connect",
    tagline: "Virtual healthcare platform for remote consultations",
    sector: "HealthTech",
    vertical: "Telemedicine",
    stage: "Seed",
    location: "Greece",
    foundingYear: 2022,
    sharesAvailablePercent: 12,
    valuation: "€7.2M",
    minInvestment: 100,
    runwayMonths: 8,
    fundingProgress: 64,
    euDomiciled: true,
    audited: false,
    founderName: "Dr. Maria Papadopoulos",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Big Pi Ventures",
    impactHeadline: "Expanding Healthcare Access Across Europe",
    businessHook:
      "Video consultations connecting patients with specialists. 3,200+ consultations completed across Greece and Cyprus.",
    sharePrice: 10.2,
    priceHistory: generatePriceHistory(8.9, 10.2, 30, 0.04),
    votingPremium: 1.4,
    votingPremiumType: "fixed",
  },
  {
    id: "30",
    name: "NeuralLink EU",
    tagline: "Brain-computer interface for medical applications",
    sector: "DeepTech",
    vertical: "Neurotechnology",
    stage: "Series A",
    location: "Switzerland",
    foundingYear: 2021,
    sharesAvailablePercent: 6,
    valuation: "€28M",
    minInvestment: 500,
    runwayMonths: 20,
    fundingProgress: 33,
    euDomiciled: true,
    audited: true,
    founderName: "Dr. Andreas Müller",
    founderTitle: "CEO & Co-founder",
    leadInvestor: "Redalpine",
    impactHeadline: "Advancing Neurotechnology in Europe",
    businessHook:
      "Non-invasive BCI helping paralyzed patients control devices. Clinical trials with 45 patients showing 78% success rate.",
    sharePrice: 26.8,
    priceHistory: generatePriceHistory(23.5, 26.8, 30, 0.024),
    votingPremium: 0.2,
    votingPremiumType: "percentage",
  },
];

export interface OpportunityFilters {
  location: string | null;
  sector: string | null;
  vertical: string | null;
  foundingYear: number | null;
  stage: string | null;
  sharesAvailableMin: number | null;
}

export const defaultFilters: OpportunityFilters = {
  location: null,
  sector: null,
  vertical: null,
  foundingYear: null,
  stage: null,
  sharesAvailableMin: null,
};

export const filterOptions = {
  locations: [...new Set(mockOpportunities.map((o) => o.location))].sort(),
  sectors: [...new Set(mockOpportunities.map((o) => o.sector))].sort(),
  verticals: [...new Set(mockOpportunities.map((o) => o.vertical))].sort(),
  foundingYears: [
    ...new Set(mockOpportunities.map((o) => o.foundingYear)),
  ].sort((a, b) => b - a),
  stages: ["Pre-Seed", "Seed", "Series A", "Series B"],
  sharesRanges: [
    { label: "Any", value: null },
    { label: "5%+", value: 5 },
    { label: "10%+", value: 10 },
    { label: "15%+", value: 15 },
  ],
};

export const collections: ThematicCollection[] = [
  {
    id: "green",
    title: "The Green Transition",
    description: "Climate technology & sustainable systems",
    icon: <Leaf className="w-5 h-5" />,
    sectors: ["CleanTech", "AgriTech"],
  },
  {
    id: "sovereignty",
    title: "European Sovereignty",
    description: "Critical infrastructure & security",
    icon: <Shield className="w-5 h-5" />,
    sectors: ["FinTech"],
  },
  {
    id: "ai",
    title: "AI for the Real World",
    description: "Healthcare & industrial automation",
    icon: <Cpu className="w-5 h-5" />,
    sectors: ["HealthTech"],
  },
];
